
# default configuration for Hanko

[modules]
    [modules.hanko]
        integration = "core"
        endpoint = ""
        login-redirect = ""
        logout-redirect = ""
        timeout-redirect = ""
    # [modules.hanko.csp]
    #     connect-src = [
    #         "" # include your endpoint here when using CSP
    #     ]
